---
- name: Check if server ready
  stat:
    path: /opt/ready.txt
  register: ready
- fail:
    msg: "Server is not ready!!!"
  when: not ready.stat.exists

- name: Copy cloud config provider flag for kubeadm
  copy:
    src: "{{ playbook_dir }}/roles/kube-prepare/files/20-hetzner-cloud.conf"
    dest: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf

- name: Reload system daemon
  shell: systemctl daemon-reload

- name: Mount BPF filesystem for cilium network plugin
  mount:
    src: bpffs
    path: /sys/fs/bpf
    fstype: bpf
    opts: defaults 0 0
    state: mounted

- name: Mark servers prepared
  file:
    path: /opt/prepared.txt
    state: touch
    mode: u+rw,g-wx,o-rwx
    modification_time: preserve
    access_time: preserve