---
- name: Check if master already created
  stat: 
    path: /opt/master.txt
  register: master

- include: tasks.yaml
  when: not master.stat.exists

- name: Create Join Command for the nodes
  shell: kubeadm token create --print-join-command
  register: join
  when: master.stat.exists

- name: Save Join to file
  local_action: copy content="{{ join.stdout }}" dest="/tmp/join.sh"
  when: master.stat.exists
  vars:
     ansible_become: no
